# Generated by Django 3.1.7 on 2021-04-17 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210417_0610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['first_name', 'last_name'], 'permissions': (('can_create_author', 'create new author'),)},
        ),
    ]
